In [1]:
import numpy as np
from fractions import Fraction

A_i = np.array([
  [-1,-1],[0,-1]
])
B_i = np.array([
  [0,1],[-1,1]
])
C = np.array([
  [0,4],[-3,-1]
])
X = A_i @ C @ B_i

A = np.array([
  [2,0,2],[-2,-2,0]
])
B = A.T @ np.linalg.inv(A @ A.T)

def inverse_as_fraction_str(A):
    # Convert to Fraction type
    A_frac = np.array(A, dtype=object)
    n = A_frac.shape[0]
    if A_frac.shape[0] != A_frac.shape[1]:
        raise ValueError("Matrix must be square to invert.")
    
    I = np.eye(n, dtype=object)
    I = np.vectorize(Fraction)(I)
    A_frac = np.vectorize(Fraction)(A_frac)
    
    # Augment [A | I]
    M = np.hstack([A_frac, I])
    
    # Gauss–Jordan elimination
    for i in range(n):
        pivot = M[i, i]
        if pivot == 0:
            raise ValueError("Matrix is singular, no inverse.")
        M[i] = [val / pivot for val in M[i]]
        
        for j in range(n):
            if j != i:
                factor = M[j, i]
                M[j] = [val - factor * piv for val, piv in zip(M[j], M[i])]
    
    # Extract inverse and format as "a/b"
    A_inv = M[:, n:]
    A_inv_str = np.array([[f"{f.numerator}/{f.denominator}" for f in row] for row in A_inv])
    return A_inv_str
A = np.array([
  [-1,-1,-2,2],
  [-2,2,-2,2],
  [1,0,0,-2],
  [-2,0,-2,-1]
])

A_inv = inverse_as_fraction_str(A)

A_inv

B = np.array([
  [-1,-2,0,-2],
  [2,1,0,2],
  [0,0,-2,0],
  [2,0,0,2]
])

inverse_as_fraction_str(B)  

A = np.array([
  [-3,0,0,0],
  [4,3,1,0],
  [0,1,0,0],
  [0,0,0,1]
])

inverse_as_fraction_str(A)

A = np.array([
  [2,0,0,0,0],
  [1/2,0,0,0,1],
  [0,0,1,0,0],
  [0,0,0,1,0],
  [0,2,0,1/4,0]
])

np.linalg.inv(A)

array([[ 0.5  ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , -0.125,  0.5  ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ],
       [-0.25 ,  1.   ,  0.   ,  0.   ,  0.   ]])

In [2]:
A = np.array([
  [0,0,0,0,1],
  [0,4,0,2,0],
  [0,0,1,0,0],
  [0,0,0,1,0],
  [1,3,0,0,0]
])

B = np.array([
  [-1,-1,-1,2,-2],
  [2,1,0,0,-2],
  [-3,0,-3,2,2],
  [-1,-3,0,-1,-3],
  [0,0,1,-1,-1]
])
np.linalg.inv(A) @ B

array([[-3.  , -5.25,  1.  , -2.5 , -4.  ],
       [ 1.  ,  1.75,  0.  ,  0.5 ,  1.  ],
       [-3.  ,  0.  , -3.  ,  2.  ,  2.  ],
       [-1.  , -3.  ,  0.  , -1.  , -3.  ],
       [-1.  , -1.  , -1.  ,  2.  , -2.  ]])

In [3]:
A = np.array([
  [20,4,1,0],
  [-10,-2,0,0],
  [1,0,0,0],
  [0,0,0,1]
])

B = np.array([
  [-2,-3,1,0],
  [-2,-1,-2,2],
  [1,2,0,-3],
  [0,-2,-1,1]
])

np.linalg.inv(A) @ B

array([[ 1. ,  2. ,  0. , -3. ],
       [-4. , -9.5,  1. , 14. ],
       [-6. , -5. , -3. ,  4. ],
       [ 0. , -2. , -1. ,  1. ]])

In [4]:
def predict(time, score = 10, difficulty = 3):
  predictedScore = time * difficulty
  return score + predictedScore


predict(60, 10, difficulty=3)

def taylor(a, b):
  return a + b
taylor(10)

TypeError: taylor() missing 1 required positional argument: 'b'

In [5]:
import numpy as np

def lu_no_pivot(A):
    A = A.astype(float)
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros_like(A)

    for i in range(n):
        # Upper-triangular part
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))
        # Lower-triangular part
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

# Example
A = np.array([
  [-2,1,-2],
  [0,-1,0],
  [2,-1,3]
])

L, U = lu_no_pivot(A)

print("A =\n", A)
print("L =\n", L)
print("U =\n", U)
# print("Check A = L @ U:\n", L @ U)


A =
 [[-2  1 -2]
 [ 0 -1  0]
 [ 2 -1  3]]
L =
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-1. -0.  1.]]
U =
 [[-2.  1. -2.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


In [6]:
import statistics
statistics.stdev( [2, 32, 32, 36, 38])
statistics.median([85, 99, 80, 80.5, 97, 87, 91.5, 86, 96.5, 91, 94.5, 95])

91.25

In [7]:
import numpy as np
import scipy as sp
x = [3, 5, 6, 7, 9, 10, 11, 12, 12, 16, 19, 20]
np.percentile(x,25)

np.float64(6.75)

In [8]:
import numpy as np

# Write your code to calculate T below this line

s = [178, 283, 105, 169, 296, 366, 334, 153, 350]

b = np.array([
    s[0] + s[1] + s[8],
    s[2],
    s[8] + s[7],
    s[3] + s[4],
    s[5] + s[6]
])


grid = np.array([
    [4,-1,0,0,0],
    [-1,4,-1,-1,0],
    [0,-1,4,0,-1],
    [0,-1,0,4,-1],
    [0,0,-1,-1,4]
])

T = np.linalg.inv(grid) @ b
T


array([256.57303371, 215.29213483, 254.54775281, 245.04775281,
       299.8988764 ])

In [9]:
import pprint
import scipy.linalg as sla
N = 6
E = np.array([9.134569904405563, 15.481413553901227, -7.331070151326191, 19.980445226043045, -10.529394402047147, -5.723531384456116])
R = np.array([3905.3848056059296, 4963.998641512828, 4570.277955754635, 9929.725845652789, 3902.169916320312, 8802.666181599428])

E = np.append(E,0)
col = np.ones((N, 1))

med = np.hstack((np.diag(R),col))

row = np.append(np.ones((1,N)),0)

A = np.vstack((med, row))
P,L,U = sla.lu(A)
Y = sla.solve_triangular(L,P.T@ E,lower=True)
I = sla.solve_triangular(U,Y,lower=False)
I

array([ 1.77695792e-03,  2.67658174e-03, -2.08432303e-03,  1.79114510e-03,
       -3.26081645e-03, -8.99545281e-04,  2.19486544e+00])

In [10]:
B = np.array([
  [-2,1,1],
  [-1,-1,-2],
  [0,0,-1]
]) 
np.linalg.inv(B.T) @ np.array([-1,1,-1])
np.linalg.inv(B.T) @ np.array([-2,2,1])

array([ 1.33333333, -0.66666667,  1.66666667])

In [11]:
I_CB = np.array([
  [0,2],
  [2,-3]
])
T_CC = np.array([
  [-2,0],
  [1,1]
])

np.linalg.inv(I_CB) @ T_CC @ I_CB

array([[ 1. , -3.5],
       [ 0. , -2. ]])

In [12]:
B = np.array([
  [-1,1,0],
  [0,-1,0],
  [-1,0,-1]
])
T = np.array([
  [-3,0,0],
  [0,1,0],
  [0,0,-2]
])
v = np.array([0,1,1])

B @ T @ np.linalg.inv(B) @ v

array([-4.,  1., -3.])

In [13]:
I_EB = np.array([
  [3,3,0],
  [3,-3,0],
  [0,0,np.sqrt(18)]
])

sla.inv(I_EB)

array([[ 0.16666667,  0.16666667, -0.        ],
       [ 0.16666667, -0.16666667,  0.        ],
       [ 0.        ,  0.        ,  0.23570226]])

In [14]:
from scipy.linalg import expm
A = np.array([
  [1,2],
  [2,1]
])

eA = expm(A)
print(eA)

[[10.22670818  9.85882874]
 [ 9.85882874 10.22670818]]


In [15]:
A = np.array([
  [-1,0],
  [2,1]
])

x0 = np.array([2,1])

eigvals, eigvecs = np.linalg.eig(A)
c = np.linalg.solve(eigvecs, x0)
eigvecs[0] * c[0] , eigvecs[1] * c[1]

(array([0.        , 2.12132034]), array([ 2.82842712, -2.        ]))

In [16]:
import numpy as np
import numpy.linalg as la

D = np.diag([.47,.51,.25])
P = np.array([
  [2,9,5],
  [2,3,9],
  [7,10,2]
])

I = np.eye(3)
B = ( P @ la.inv(D) @ la.inv(P) ) + I
eigvals, Q = la.eig(B)
C = np.diag(eigvals)
C, Q

A = np.array([
  [-8,-3],
  [18,7]
])

x0 = np.array([
  2,1
])

val, vec = la.eig(A)
c = np.linalg.solve(vec, x0)
val, c

(array([-2.,  1.]), array([-15.65247584, -15.8113883 ]))

In [51]:
import numpy as np
from scipy.linalg import null_space


def project_to_subspace(v, W):
    """
    将向量 v 投影到由 W 的列向量张成的子空间上。
    v: shape (n,)
    W: shape (n, k)
    返回: v 在 span(W) 上的投影向量
    """
    W = np.array(W, dtype=float)
    v = np.array(v, dtype=float)

    # 投影公式: P = W (W^T W)^(-1) W^T v
    P = W @ np.linalg.inv(W.T @ W) @ W.T
    return P


x = np.array([-2, -1, 1])

u1 = np.array([1, -1, -2, 0, -2])
u2 = np.array([0, 0, 1, -2, -1])
U = np.column_stack((u1, u2))  # shape (5, 2)

# Find the orthogonal complement (null space of U^T)
U_perp = null_space(U.T)

import subprocess
import time


def copy_matrix_cells_reverse(matrix, delay=2, use_pbcopy=True):
    """
    依次（倒序）复制矩阵的每个元素到剪贴板。

    参数：
    - matrix: 2D numpy array 或可转换为 array 的对象
    - delay: 每次复制间的时间间隔（秒）
    - use_pbcopy: True 使用 macOS pbcopy；False 只打印内容
    """
    arr = np.array(matrix)
    rows, cols = arr.shape

    # 倒序遍历：从右下角到左上角
    for r in range(0, rows, 1):
      for c in range(0, cols, 1):
    # for r in range(rows - 1, -1, -1):
    #     for c in range(cols - 1, -1, -1):
            val = str(arr[r, c])
            if use_pbcopy:
                subprocess.run("pbcopy", text=True, input=val)
            print(f"Copied cell ({r+1},{c+1}) -> {val}")
            time.sleep(delay)


# print("Orthonormal basis for U⊥:")
# print(U_perp)
# print("Dimension of U⊥ =", U_perp.shape[1])

A = U_perp[:, :2]  # take any two independent vectors
print("Matrix A:\n", A)
print("Rank of A =", np.linalg.matrix_rank(A))
copy_matrix_cells_reverse(A)

Matrix A:
 [[ 0.50335609  0.25819889]
 [-0.52918114  0.7544635 ]
 [ 0.59146764  0.20926718]
 [ 0.33333333  0.33333333]
 [-0.07519903 -0.45739949]]
Rank of A = 2
Copied cell (1,1) -> 0.5033560871600952
Copied cell (1,2) -> 0.2581988897471611
Copied cell (2,1) -> -0.5291811373945343
Copied cell (2,2) -> 0.7544635041298856
Copied cell (3,1) -> 0.5914676394719908
Copied cell (3,2) -> 0.20926717973765238
Copied cell (4,1) -> 0.3333333333333334
Copied cell (4,2) -> 0.33333333333333315
Copied cell (5,1) -> -0.07519902719467579
Copied cell (5,2) -> -0.45739948692901444


In [56]:
A = np.array([
  [-1,-1],
  [-1,-1],
  [-1,-1],
  [0,-1]
])
b = np.array([
  -1,0,0,-1
])
print(A.T @ A, A.T @ b)
xbar = la.solve(A.T @ A, A.T @ b)
print(xbar)
A @ xbar

[[3 3]
 [3 4]] [1 2]
[-0.66666667  1.        ]


array([-0.33333333, -0.33333333, -0.33333333, -1.        ])

In [62]:
A = np.array([
  [1,-1,0],
  [-2,3,1],
  [1,-1,0]
])
b = np.array([-1,3,-3])
x1bar = np.array([-1,1,-2])
la.lstsq(A.T @ A, A.T @b)

(array([-1.66666667,  0.33333333, -1.33333333]),
 array([], dtype=float64),
 np.int32(2),
 array([1.76602540e+01, 3.39745962e-01, 6.54613008e-16]))

In [ ]:
import numpy as np
import sympy as sp

# HW 2

## Question HW2.2

In [ ]:
A1 = np.array(
  [[-2,-3],[4,-2]]
)
A2 = np.array(
  [[4,-2],[3,-2]]  
)
A3 = np.array(
  [[4,-3],[-3,1]]
)
B = np.array(
  [[2,2],[0,0]]
)
a1 = A1.flatten()
a2 = A2.flatten()
a3 = A3.flatten()
b  = B.flatten()
M = np.column_stack([a1, a2, a3])
c, residuals, rank, s = np.linalg.lstsq(M, b, rcond=None)
if residuals.size == 0 or np.allclose(residuals, 0):
    print("Yes, B is a linear combination.")
    print("Coefficients:", c)
else:
    print("No, B is not a linear combination.")



No, B is not a linear combination.


## Question HW1.5

In [ ]:
def output_RREF(A: sp.Matrix):
  R, pivots = A.rref()   # RREF and pivot column indices

  print("RREF:")
  sp.pprint(R)

  print("Pivot columns:", pivots)
# Example
A1 = sp.Matrix([
  [-2,0,-1,1,-2,-3],
  [-1,1,-2,-1,1,-3],
  [0,-1,-2,-2,1,-2]
], dtype=float)


A2 = sp.Matrix([
  [-1,-2,1,4,2,0],
  [0,-2,-1,1,0,-1],
  [1,1,-1,-3,-3,0]
], dtype=float)

output_RREF(A2)

RREF:
⎡1  0  0  -1  -6  1⎤
⎢                  ⎥
⎢0  1  0  -1  1   0⎥
⎢                  ⎥
⎣0  0  1  1   -2  1⎦
Pivot columns: (0, 1, 2)


## Question HW1.6

In [ ]:
A3 = sp.Matrix(
  [
    [0,0,0,0],
    [0,0,0,0],
    [0,0,1,1],
    [0,0,-2,-2]
  ]
)

output_RREF(A3)

RREF:
⎡0  0  1  1⎤
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎣0  0  0  0⎦
Pivot columns: (2,)


In [ ]:
# Example matrix
A = sp.Matrix([
  [-2,0,-1,0,0],
  [-3,-1,1,3,1],
  [1,1,1,-1,1],
  [1,-1,0,0,1],
  [-1,1,2,0,3]
])

# Null space of A
nullA = A.nullspace()
print("Null space of A:", nullA)

# Null space of A^T = orthogonal complement of Col(A)
nullAT = A.T.nullspace()
print("Null space of A^T (orthogonal complement of Col(A)):", nullAT)


Null space of A: [Matrix([
[ 1],
[ 2],
[-2],
[ 2],
[ 1]])]
Null space of A^T (orthogonal complement of Col(A)): [Matrix([
[-2/3],
[-2/3],
[  -2],
[-1/3],
[   1]])]


## Else

$$
CAD = C \cdot (AD) = C\cdot I_m = C
$$

$$
CAD = (CA) \cdot D = I_n \cdot D = D
$$

$$
\therefore C = CAD = D
$$

In [ ]:
import sympy as sp

# Define the symbol and matrix
λ = sp.symbols('λ')
A = sp.Matrix([
  [0,0,0],
  [-1,1,4],
  [0,0,-3]
])

# Compute the characteristic polynomial
char_poly = A.charpoly(λ)

print("Characteristic Polynomial:", char_poly.as_expr())
print("Coefficients:", char_poly.all_coeffs())


Characteristic Polynomial: λ**3 + 2*λ**2 - 3*λ
Coefficients: [1, 2, -3, 0]


In [ ]:
[
  [0,1,0,0],
  [0,0,0,0],
  [0,0,0,0],
  [0,0,1,0]
]

[[0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0]]

Known: If $\mathcal{B}$ is a basis of $W$, and $\mathcal{B}$ has $p$ vectors, then $\forall m>p$, matrices with $m$ vectors can't be a basis of $W$.

Suppose $\mathcal{B}_1, \mathcal{B}_2$ are two basis, and $\mathcal{B}_1$ has $m$ vectors and $\mathcal{B}_2$ has $p$ vectors, where $m>p$. Since $\mathcal{B}_2$ is a basis, from *Known*, $\mathcal{B}_1$ can't be a basis.

Thus there can't be two basis that one has a greater number of basis than the other.
Hence the number of vectors in all basis of $W$ should be the same.

In [ ]:
T = np.array([
  [2/4,2/4,0],
  [3/4,1/4,0],
  [3/4,0,1/4]
])
T = T.T

def power_iteration(M, x):
    # Perform power iteration and return steady state vector xstar
    xc = x.copy()
    for i in range(100):
        xc = M @ xc
    return xc

x = np.array([0,1,0])

power_iteration(T, x)

T_BullBearS = np.array([
  [0.75,0.05,0.2],
  [0.25,0.5,0.25],
  [0.2,0.4,0.4]
])
T_BullBearS = T_BullBearS.T

power_iteration(T_BullBearS,x)

array([0.47337278, 0.26035503, 0.26627219])

In [ ]:
A = np.array([
  [-.5,1.5,1],
  [.5,.5,1],
  [-.5,1.5,1]
])
eigvals, eigvecs = np.linalg.eig(A)

# 构造 D 和 P
D = np.diag(eigvals)
P = eigvecs

print("P =\n", P)
print("D =\n", D)

P =
 [[-0.57735027  0.57735027  0.57735027]
 [ 0.57735027  0.57735027  0.57735027]
 [-0.57735027 -0.57735027  0.57735027]]
D =
 [[-1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.15589687e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+00]]


In [ ]:
import numpy as np
def least_sq(A, y):
    # Find the least squares solution to Ax = y
    # by solving Rx = Q^T y for x where A = QR
    Q,R = np.linalg.qr(A)
    x = np.linalg.solve(
        R, Q.T @ y
    )
    return x
def linear_xy(x_y= [(-2, 1), (1, 1), (2, 1), (1, -1), (-1, 0), (-1, -2)]):
  x_line, y_line = [], []
  for x,y in x_y:
    x_line.append(x)
    y_line.append(y)
  A = np.array([
    np.ones(len(x_line)), x_line
  ]).T

  return A.T @ A, A.T @ y_line, least_sq(A, y_line)

x_y = [(2, 4), (-2, 2), (-1, 4), (-1, -3), (2, 4)]
x_line, y_line = [], []
for x,y in x_y:
  x_line.append(x)
  y_line.append(y)
x_line, y_line = np.array(x_line), np.array(y_line)
A = np.array([
  np.ones(x_line.shape),
  x_line,
  x_line**2
]).T
A, A.T @ A, A.T @ y_line, least_sq(A, y_line)

(array([[ 1.,  2.,  4.],
        [ 1., -2.,  4.],
        [ 1., -1.,  1.],
        [ 1., -1.,  1.],
        [ 1.,  2.,  4.]]),
 array([[ 5.,  0., 14.],
        [ 0., 14.,  6.],
        [14.,  6., 50.]]),
 array([11., 11., 41.]),
 array([0.33333333, 0.5       , 0.66666667]))

Vampire the Mascura

In [ ]:
import numpy as np
D = np.array([
  [-5,0],
  [0,-3]
])
P = np.array([
  [1,-5],
  [-1,6]
]).T
P @ D @ np.linalg.inv(P)

array([[-15.,  -2.],
       [ 60.,   7.]])

So I may say that, the singular value decomposition of $A$ is linking the normal eigenvectors of $A$ in both $\mathbb{R}^m$ and $\mathbb{R}^n$.

## midterm3_prep

In [ ]:
import numpy as np
import numpy.linalg as la
T_BB = np.array([
  [1,1],
  [1,1]
])
I_BC = np.array([
  [-1,0],
  [0,2]
])
T_CC = la.inv(I_BC) @ T_BB @ I_BC
T_CC