In [6]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
## important steps
U, S, Vh = la.svd(A)
m, n = U.shape[1], Vh.shape[0]
Sigma = np.zeros((m,n))
np.fill_diagonal(Sigma, S)
U, S, Vh

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

In [7]:
UR, SR, VRt = la.svd(A, full_matrices=False)
UR, SR, VRt

(array([[-0.2298477 ,  0.88346102],
        [-0.52474482,  0.24078249],
        [-0.81964194, -0.40189603]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

In [ ]:
np.outer